import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form action='/api/form' method='post'>
          <label htmlFor='first'>First name</label>
          <input type='text' id='first' name='first' required />
          <br />

          <label htmlFor='last'>Last name</label>
          <input type='text' id='last' name='last' required />

          <br />
          <button type='submit'>Submit</button>
        </form>
      </main>
    </>
  )
}
